final products = [
  {
    'id': '0',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoe_1.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_2.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoe_3.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoe_4.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoe_5.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '5',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoe_6.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '6',
    'title': 'Bata Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_7.png',
    'company': 'Bata',
    'sizes': [9, 10, 12],
  },
  {
    'id': '7',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoe_8.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '8',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_9.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '9',
    'title': 'Bata Women\'s Shoes',
    'price': 28.95,
    'imageUrl': 'assets/images/shoe_10.png',
    'company': 'Bata',
    'sizes': [8, 9, 10],
  },
  {
    'id': '10',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoe_11.png',
    'company': 'Addidas',
    'sizes': [8, 9, 10],
  },
  {
    'id': '11',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/shoe_12.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '13',
    'title': 'Men\'s Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/shoe_13.png',
    'company': 'Nike',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '14',
    'title': 'Addidas Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_14.png',
    'company': 'Addidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '15',
    'title': 'Nike Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_15.png',
    'company': 'Nike',
    'sizes': [9, 10, 12],
  },
  {
    'id': '16',
    'title': 'Nike Shoes',
    'price': 20.12,
    'imageUrl': 'assets/images/shoe_16.png',
    'company': 'Nike',
    'sizes': [9, 10, 12],
  },
];
